### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by kangning1206** [jacklam718/react-native-button-component#1]
error
react-native-button-component/index.js:__DEV__ is not defined
![Uploading image.png…]()

**Comment by DennisMG** [comment]
Did you fix the problem?

**Comment by jacklam718** [comment]
@DennisMG I saw @kangning1206 closed this issue, so I thought this component is working now.

**Comment by jacklam718** [comment]
@DennisMG 
You also have this issue? If so, can you give me more info?

1. What version of this package are you installing?
2. What version of react native are you using?
3. What version of react are you using?
4. What platform of your device, IOS / Android? What version of the OS?
5. Did you follow the installation instructions?
6 Any other errors appear in the debug console? If so, can you post all of the log here?
