### ISSUE TITLE
react-native link doesn't work properly

### ISSUE THREAD

**Issue by kis25791** [jacklam718/react-native-button-component#11]
After installing your lib, then I ran "react-native link" but seems it doesn't work.
"Spin-kit" was not linked and I have to do manually after headache hours.

Can you please check again this feature?

**Comment by jacklam718** [comment]
@kis25791 
try to run this command `react-native link eact-native-linear-gradient` AND `react-native link react-native-spinkit`

**Comment by jacklam718** [comment]
@kis25791 Did you try? Is it work?

**Comment by kis25791** [comment]
Yep @jacklam718 , that is the way I did manually

**Comment by jacklam718** [comment]
@kis25791 I've written a script for that. But the script can't run on Windows so at the moment we need manually run link command

**Comment by kis25791** [comment]
Actually I ran in OSX :D So does it work in OSX

**Comment by jacklam718** [comment]
@kis25791 I solved the problem in version `v0.1.16` so now we can just run `react-native link` then it will automatically link all native dependencies.
