### ISSUE TITLE
I can't run this on android

### ISSUE THREAD

**Issue by dreamsparkx** [jacklam718/react-native-button-component#14]
I can't run this on android.
Please can someone explain me how to use this in android?

**Comment by jacklam718** [comment]
@dreamsparkx what error you got?

**Comment by yuraxdrumz** [comment]
Hey, I'm not seeing anything as well on android, no errors, nothing happens

**Comment by jacklam718** [comment]
sorry, I have no idea 😐

**Comment by Unforgiven-wanda** [comment]
Same issue as @jacklam718, not to mention that the example shipped with this repo does not work.
The components look really sleek,hoping you'll fix it soon.

**Comment by jacklam718** [comment]
@dreamsparkx seems this is duplicated with issue [#13](https://github.com/jacklam718/react-native-button-component/issues/13) 
BTW: I have fixed the issue on version `0.1.17`
