### ISSUE TITLE
Error linking module

### ISSUE THREAD

**Issue by tafelito** [jacklam718/react-native-button-component#16]
Hi, I tried to use this package but when I do the link it throws this error and it won't build 
```
child_process.js:526
    throw err;
    ^

Error: Command failed: node node_modules/react-native/local-cli/cli.js link react-native-spinkit && node node_modules/react-native/local-cli/cli.js link react-native-linear-gradient
rnpm-install info Linking react-native-spinkit android dependency
rnpm-install info Android module react-native-spinkit has been successfully linked
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
```

I'm using RN Version 0.44 on Android 6.0

**Comment by jacklam718** [comment]
@tafelito may I know what OS you use? Windows/Linux/Mac OS X ?

**Comment by tafelito** [comment]
I use Mac, and RN 0.44 if that helps

**Comment by jacklam718** [comment]
@tafelito Some people has same issue. FYI https://github.com/facebook/react-native/issues/10032

**Comment by tafelito** [comment]
@jacklam718 That looks like an iOS issue. I'm testing it on Android, and it doesn't seem to be linking the libraries either

**Comment by jacklam718** [comment]
@tafelito 
You can try manually link those libraries. for example:
`react-native link react-native-spinkit`
`react-native link react-native-linear-gradient`

can you let me know the result if you tried? thanks!

**Comment by tafelito** [comment]
@jacklam718 Same issue linking those manually. And as it says on the bug you mentioned before, thats an error looks like is on the iOS `project.pbxproj` file. Not sure how's that related to Android though

```
/.../android/app/src/main/java/com/.../MainApplication.java:27: error: cannot find symbol
            new LinearGradientPackage(),
                ^
  symbol: class LinearGradientPackage
/.../android/app/src/main/java/com/.../MainApplication.java:28: error: cannot find symbol
            new RNSpinkitPackage()
                ^
  symbol: class RNSpinkitPackage
2 errors
:app:compileDebugJavaWithJavac FAILED
```

**Comment by tafelito** [comment]
OK nvm, looks like its working now. The error was just the imports on the android project. Not sure why the link does not add them to the `MainApplication.java` 

Thanks!

**Comment by tafelito** [comment]
Ok Actually, it didn't throw any error, but the component still not working. It just don't show anything. I used the the One State Button example and this is what it looks like

![screenshot_20170526-161801](https://cloud.githubusercontent.com/assets/5973652/26511224/17056f92-422f-11e7-8f82-2699011cfe0f.png)

**Comment by jacklam718** [comment]
@tafelito Did you linked those libraries?

**Comment by tafelito** [comment]
@jacklam718  I jus created a new project from scratch and it did work, so I'll have to see what are the differences with my current project and why the linking didn't work. 

Thanks!

**Comment by jacklam718** [comment]
@tafelito 🤔 
I think you can try to delete `node_modules` and install again.
