### ISSUE TITLE
undefined is not an object (evaluating 'currentButtonState.gradientStart')

### ISSUE THREAD

**Issue by jfoc2009** [jacklam718/react-native-button-component#2]
My source code:

...
this.state = {
	buttonState: 'entrar',
};

this.states = {
	login: {
		text: 'Entrar'.toUpperCase(),
		onPress: this.doLogin,
	},
	onLogin: {
		spinner: true,
		gradientStart: [0.8, 1],
		gradientEnd: [1, 1],
		spinnerColor: '#000000',
		text: 'Autenticando...'.toUpperCase(),
	},
	success: {
		text: 'Autenticado 👍'.toUpperCase(),
	},
...

<RoundButton
	buttonState={this.state.buttonState}
	states={this.states}
/>

or

using ButtonComponent instead RoundButton.

**Comment by jacklam718** [comment]
@jfoc2009 
Your buttonState is `entrar` but you didn't defined `entrar` on the states object.

If you buttonState is `entrar` then you must defined the `entrar` object on states object, like the following.

this.states = {
  login: {
    text: 'Entrar'.toUpperCase(),
    onPress: this.doLogin,
  },
  onLogin: {
    spinner: true,
    gradientStart: [0.8, 1],
    gradientEnd: [1, 1],
    spinnerColor: '#000000',
    text: 'Autenticando...'.toUpperCase(),
  },
  success: {
    text: 'Autenticado 👍'.toUpperCase(),
  },
  entrar: {
     text: 'Entrar',
  },


@jfoc2009 Do you understand?

**Comment by jfoc2009** [comment]
@jacklam718 I got it! Thanks so much...
