### ISSUE TITLE
Couldn't find preset "react-native-stage-0" 

### ISSUE THREAD

**Issue by KaelThasWang0919** [jacklam718/react-native-button-component#24]
Error: Couldn't find preset "react-native-stage-0" relative to directory "/Users/kaelthas/****/node_modules/react-native-button-component"

**Comment by jacklam718** [comment]
@KaelThasWang0919 Fixed in **v0.1.22**

**Comment by KaelThasWang0919** [comment]
I'm using it

**Comment by jacklam718** [comment]
@KaelThasWang0919 Works, right?

**Comment by KaelThasWang0919** [comment]
This error occurs when I use "react-native:0.44.0" .

"react-native": "0.47.1", Works!
