### ISSUE TITLE
Buttons disappear when being in a row oriented container.

### ISSUE THREAD

**Issue by Dantalion** [jacklam718/react-native-button-component#27]
Whenever I put multiple buttons next to each other in one row using 
` flexDirection: 'row'` 
on the view surrounding them they just disappear.

Normal column alignment works fine.

**Comment by Dantalion** [comment]
When I assign a fixed width it works, but is there no option to just let them automatically take 50% (in case of 2 buttons) of the width automatically for better results?

**Comment by Dantalion** [comment]
Ok there was a mistake in my layout...
It works when assigning width or also when assigning correct flex ratios....

**Comment by dmexs** [comment]
Just to help anybody else who has this issue, I was able to make it work by making sure my buttons were each wrapped in their own views with flex ratios set:

          <View style={{flexDirection: 'row', flex: 1}}>
            <View style={{flex: 1, paddingRight: 5}}>
              <RoundButton
                type='secondary'
                text='Register'
              />
            </View>
            <View style={{flex: 1, paddingLeft: 5}}>
              <RoundButton
                type='secondary'
                text='Forgot Password'
              />
            </View>
          </View>
