### ISSUE TITLE
SpinnerType

### ISSUE THREAD

**Issue by itswaze** [jacklam718/react-native-button-component#30]
It's not really an issue, but I've searched and couldn't find all the spinner types available.
I know the default one is "wave", but is that the only one? or there is more?

**Comment by jacklam718** [comment]
@itswaze This component is using this library [react-native-spinkit](https://github.com/maxs15/react-native-spinkit) You can take a look.

**Comment by itswaze** [comment]
that's it, thank you :)

**Comment by itswaze** [comment]
@jacklam718  btw, how can I remove the text and only show the spinner? I can remove the text on "onLogin" but the spinner won't center.

**Comment by jacklam718** [comment]
@itswaze I didn't think about it. I really appreciate your opinion!
