### ISSUE TITLE
Cannot apply styles in text of the button by buttonStyle

### ISSUE THREAD

**Issue by duydtd97** [jacklam718/react-native-button-component#37]
I have this component:
`<ButtonComponent

          text="LOG IN"
          type="primary"
          shape="rectangle"
          backgroundColors={['#F9D218', '#FF9D5D']}
          gradientStart={{ x: 0.5, y: 1 }}
          gradientEnd={{ x: 1, y: 1 }}
          height={60}
          buttonStyle={styles.btnLogin}
          onPress={() => {alert('pressed me')}}
        >
        </ButtonComponent>`

and its styles : 
`btnLogin:{
    fontSize:30,
    borderRadius:8,
    fontWeight: "700",
    color:'#000'
  }`

Button just apply borderRadius property but the rest (fontSize, fontWeight, color) is not.

**Comment by pixelize** [comment]
@duydtd97 would you explain how did you solved your problem please ? :P I  think textStyle prop can make the job ?
