### ISSUE TITLE
Dependencies don't support React Native >= 0.40

### ISSUE THREAD

**Issue by elyscape** [jacklam718/react-native-button-component#5]
React Native's 0.40.0 release [included breaking changes for iOS][changes].

This package has a dependency on [react-native-linear-gradient] at `^1.5.15`, which works for previous versions of React Native but not on the current one. Version 2.0.0 of react-native-linear-gradient has been updated to work with React Native 0.40.0, though.

This package also depends on [react-native-spinkit] at `^0.1.5`. React Native 0.40 support was added in version 1.0.0 of the package.

[changes]: https://github.com/facebook/react-native/releases/tag/v0.40.0
[react-native-linear-gradient]: https://github.com/react-native-community/react-native-linear-gradient
[react-native-spinkit]: https://github.com/maxs15/react-native-spinkit

**Comment by jacklam718** [comment]
@elyscape Thank you let me know this. I will upgrade those package versions.

**Comment by jacklam718** [comment]
@elyscape I've just updated those package versions, now this this package should be supported React Native >= 0.4.0
