### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by noprom** [jacklam718/react-native-button-component#7]
I got this error after installing your component:
<img width="651" alt="qq20170207-151442 2x" src="https://cloud.githubusercontent.com/assets/8455444/22681459/48c278cc-ed48-11e6-820c-5c4da3d4a290.png">
But the `react-native-spinkit` module already exists in my project, and it links successfully:
<img width="302" alt="2" src="https://cloud.githubusercontent.com/assets/8455444/22681499/8d3fad9e-ed48-11e6-85cb-a915ddfd622e.png">
<img width="631" alt="3" src="https://cloud.githubusercontent.com/assets/8455444/22681587/049407f0-ed49-11e6-99c8-eb6495636859.png">

I'd appreciate it if you could offer any help, thanks in advance.

**Comment by jacklam718** [comment]
@noprom 
You can try to remove `React`

`#import <React/RCTViewManager.h>` --> `#import <RCTViewManager.h>`

**Comment by noprom** [comment]
@jacklam718 
Thanks, it works, but it's a part of the dependency `RNSpinkit`, is there any better solution?

**Comment by jacklam718** [comment]
@noprom 
What version of React and React Native are you using?
