### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by jjhesk** [jacklam718/react-native-button-component#9]
i install the module and linked successfully with the `libART.a` file but it is still not working. 
current versionL: `0.1.13`
RN: `0.41.2`

**Comment by jacklam718** [comment]
@jjhesk 
Please give me more detailed description.
What problem?
What error messages?
What OS and Version?

**Comment by jjhesk** [comment]
@jacklam718 there is no error. target 8.0, iOS 10.2, iphone 6

**Comment by jacklam718** [comment]
@jjhesk Can you show me your config?

**Comment by zuzuviewer** [comment]
me too;it is did not work

**Comment by jacklam718** [comment]
@zuzuviewer can you show me your code and send me a screenshot?

**Comment by zuzuviewer** [comment]
`<View style={[Style.flexAll,Style.center,{height:400,width:200}]}>
                <Text>你好</Text>
                <CircleButton
                    size={100}
                    shape="circle"
                    buttonState="opened"
                    states={{
                            closed:{
                                text:'休业中',
                                backgroundColors: ['#4DC7A4', '#66D37A'],
                                onPress:this.toOpen,
                            },
                            opening:{
                                text:'正在开门...',
                                backgroundColors: ['#6A6AD5', '#6F86D9'],
                            },
                            opened:{
                                text:'营业中',
                                backgroundColors: ['#ff4949', '#fe6060'],
                                onPress:this.toClose,
                            },
                            closing:{
                                text:'正在关门...',
                                backgroundColors: ['#6A6AD5', '#6F86D9'],
                            },
                        }
                        } />
                <Text>结尾</Text>
            </View>`
my RN is 0.39.2 ,Android is MIUI8.2,upload screenshot image failed,so I tell you "你好" and "结尾" are all normally to been showed`<View style={[Style.flexAll,Style.center,{height:400,width:200}]}>
                <Text>你好</Text>
                <CircleButton
                    size={100}
                    shape="circle"
                    buttonState="opened"
                    states={{
                            closed:{
                                text:'休业中',
                                backgroundColors: ['#4DC7A4', '#66D37A'],
                                onPress:this.toOpen,
                            },
                            opening:{
                                text:'正在开门...',
                                backgroundColors: ['#6A6AD5', '#6F86D9'],
                            },
                            opened:{
                                text:'营业中',
                                backgroundColors: ['#ff4949', '#fe6060'],
                                onPress:this.toClose,
                            },
                            closing:{
                                text:'正在关门...',
                                backgroundColors: ['#6A6AD5', '#6F86D9'],
                            },
                        }
                        } />
                <Text>结尾</Text>
            </View>`
my RN is 0.39.2 ,Android is MIUI8.2,upload screenshot image failed,so I tell you "你好" and "结尾" are all normally to been showed

**Comment by jjhesk** [comment]
@jacklam718 did you make the fix?

**Comment by jjhesk** [comment]
it is working now.

**Comment by jacklam718** [comment]
@jjhesk 
Just curious, how do you fix?

**Comment by zuzuviewer** [comment]
@jacklam718 did you make the fix?

**Comment by jacklam718** [comment]
@zuzuviewer 
I have no idea.

Can you try installing this version `v0. 1.15` and then run these commands?
`react-native link react-native-spinkit`
`react-native link react-native-linear-gradient`

**Comment by zuzuviewer** [comment]
The result is still the same

**Comment by jacklam718** [comment]
@zuzuviewer Oh~~ So sorry!

**Comment by zuzuviewer** [comment]
I installed the version v0.1.12 and it is working

**Comment by jjhesk** [comment]
@jacklam718 @zuzuviewer yes, the library did not linked properly for the libBVLinearGradient.a on xcode 8. I did it with yarn.

**Comment by jacklam718** [comment]
@jjhesk You mean you had to run the command `react-native link react-native-linear-gradient` and then you still need to manually drag and drop the `BVLinearGradient.xcodeproj` into the library folder in the navigation panel?
